### ISSUE TITLE
Couldn't load plugin 'timeseriesviewerplugin' due to an error when calling its classFactory() method

### ISSUE THREAD

**Issue by tramsauer** [jakimowb/eo-time-series-viewer#1]
Hi @jakimowb ,

thank you for your work! I have tried to use the `eo-time-series-viewer` and encountered the following error after installing the plugin in QGIS (via plugin explorer) :

`Couldn't load plugin 'timeseriesviewerplugin' due to an error when calling its classFactory() method`

Traceback:
```
AssertionError 
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/qgis/utils.py", line 423, in _startPlugin
    plugins[packageName] = package.classFactory(iface)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tramsauer/.local/share/QGIS/QGIS3/profiles/default/python/plugins/timeseriesviewerplugin/__init__.py", line 39, in classFactory
    return EOTimeSeriesViewerPlugin(iface)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tramsauer/.local/share/QGIS/QGIS3/profiles/default/python/plugins/timeseriesviewerplugin/eotimeseriesviewer/eotimeseriesviewerplugin.py", line 53, in __init__
    eotimeseriesviewer.initAll()
  File "/home/tramsauer/.local/share/QGIS/QGIS3/profiles/default/python/plugins/timeseriesviewerplugin/eotimeseriesviewer/__init__.py", line 114, in initAll
    registerEditorWidgets()
  File "/home/tramsauer/.local/share/QGIS/QGIS3/profiles/default/python/plugins/timeseriesviewerplugin/eotimeseriesviewer/qgispluginsupport/qps/__init__.py", line 144, in registerEditorWidgets
    assert isinstance(classificationSchemeEditorWidgetFactory(True), ClassificationSchemeWidgetFactory)
AssertionError
```

this points to:
https://github.com/EnMAP-Box/qgispluginsupport/blob/4a9f02cb3db41781ed968691f990607a4f2137a6/qps/__init__.py#L144

My System:
Python version: 3.11.5 (main, Sep  2 2023, 14:16:33) [GCC 13.2.1 20230801] 
QGIS version: 3.32.2-Lima Lima, exported 
on Linux (Manjaro)

Thank you for considering fixing the issue.

**Comment by tramsauer** [comment]
when reconsidering, this potentially should have been opened in 
https://github.com/EnMAP-Box/qgispluginsupport/issues
... :thinking:

**Comment by jakimowb** [comment]
has been fixed with release of EOTSV 2.0
